### ISSUE TITLE
Unordered ToDos 2 (Evaluation 2)

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/GSoC17_publishing_workflow#35]
Workflow
--------
- Show Delete button only if the filter state == trashed
- Published should be default
- Setting default with an already existing default leads to an empty error (perhaps look, what in the menu happens)
- time is not correct
- don't show trashed items (only when the filter state is set to trashed)
- filter state doesn't work
- filter author doesn't work
- search clear doesn't work
- add sort "create at"
- table footer has not hte correct colspan

Status
------
- default is required (=> error when not chosen)
- two defaults are possible
- Saving a state and go back to the list: sub menu is not correct (=> extension is empty)
- needs publish/unpublish/trashed state + button + filter
- clear does not work (search)
- clicking on the "default button" in the list => empty page

Transitions
-----------
- Show delete only when state filter == trashed
- state filter is missing
- Choosing the same state for from/to delivers an empty error
- published state should be default
- State filter (from/to) does not filter correctly (shows all states instead of the one from the workflow)
- sort by status doesn't work (or dies the status column needs a "filter link", too?)
- ACL create?

**Comment by jjaracz** [comment]
Workflow
--------
- filter state doesn't work **(What you mean about that? In list of workflows i don't have state to filter of)**
- filter author doesn't work **(I have problem with that ... How to fill list of authors correctly? I'm trying to copy things from com_content but that doesn't works :/ Maybe somewhere in the core is calling getAuthors from model of com_content? I don't know)**
- search clear doesn't work **(I can't figure out how to do that, i can't find that in other components)**
- table footer has not the correct colspan **(Could you explain? If you mean the space in the bottom, in all components is that :) )**

Status
------
- Saving a state and go back to the list: sub menu is not correct (=> extension is empty) **(I don't have that issue, could you describe more?)**
- needs publish/unpublish/trashed state + button + filter **(For what there could be? I decide to not implement there that because i was not see for what that could be)**
- clear does not work (search) **(Same as in workflow)**

Transitions
-----------
- Choosing the same state for from/to delivers an empty error **(Why choosing the same state shouldn't deliver error?)**
- ACL create? **(Only create is missing? I delete some of them because in previous todo you say to clear that :D)**

**Comment by bembelimen** [comment]
Workflow
--------
> - filter state doesn't work **(What you mean about that? In list of workflows i don't have state to filter of)**

![grafik](https://user-images.githubusercontent.com/1229869/28160807-9dcd19d2-67c1-11e7-98e5-24963acdd4aa.png)
I filtered for "trashed", but the published are stilll visible + as default only published/unpublished should be visible + if there is any filter active, the filter section should stay open on page reload.

> - table footer has not the correct colspan **(Could you explain? If you mean the space in the bottom, in all components is that :) )**

![grafik](https://user-images.githubusercontent.com/1229869/28160938-fba30f8a-67c1-11e7-9c67-07d4afed55e5.png)
There are 9 columns, but you set colspan to "6", so the footer line is not 100%.

Status
------
> - Saving a state and go back to the list: sub menu is not correct (=> extension is empty) **(I don't have that issue, could you describe more?)**

![grafik](https://user-images.githubusercontent.com/1229869/28161016-37091b8c-67c2-11e7-9a64-23e284e8d05a.png)
States list => left submenu OK (beside, that the blue menu is not open, but that's another issue)
=> edit a state
![grafik](https://user-images.githubusercontent.com/1229869/28161078-6dac9970-67c2-11e7-8534-5c6cca5d3a29.png)
=> save close
![grafik](https://user-images.githubusercontent.com/1229869/28161094-7eecc8f4-67c2-11e7-8ff4-35b749b4c6b5.png)

> - needs publish/unpublish/trashed state + button + filter **(For what there could be? I decide to not implement there that because i was not see for what that could be)**

OK, perhaps in the future

Transitions
-----------
> - Choosing the same state for from/to delivers an empty error **(Why choosing the same state shouldn't deliver error?)**
![grafik](https://user-images.githubusercontent.com/1229869/28161169-c0806fdc-67c2-11e7-97f6-de97ae0603ca.png)

The fact, that there is an error is OK, but there is no error message.
> - ACL create? **(Only create is missing? I delete some of them because in previous todo you say to clear that :D)**

The question here is: what should this "create" action do? where is it used?

**Comment by bembelimen** [comment]
> - filter author doesn't work **(I have problem with that ... How to fill list of authors correctly? I'm trying to copy things from com_content but that doesn't works :/ Maybe somewhere in the core is calling getAuthors from model of com_content? I don't know)**

https://github.com/joomla-projects/GSoC17_publishing_workflow/pull/36

**Comment by jjaracz** [comment]
Workflow
--------
- filter author doesn't work

Status
------

Transitions
-----------
